show_reminder_app/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :channels
  resources :shows

  get 'search', to: 'shows#search'

  root 'welcome#index'

end

show_reminder_app/app/models/channel.rb
class Channel < ActiveRecord::Base
  validates :title, presence: true

  has_many :shows
end

show_reminder_app/app/models/show.rb
class Show < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :channel

  def self.getSearchedShows(query)
    self.joins(:channel).where("lower(channels.title) LIKE '%#{query}%' OR lower(shows.title) LIKE '%#{query}%'")
  end
end

show_reminder_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

show_reminder_app/app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  def index
    @channels = Channel.all
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      redirect_to @channel
    else
      render 'new'
    end
  end

  def show
    @channel = Channel.find_by(id: params[:id])
  end

  private

  def channel_params
    params.require(:channel).permit(:title, :favorite)
  end
end

show_reminder_app/app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  def index
    @shows = Show.all
  end

  def new
    @show = Show.new
    @channels = Channel.all
  end

  def create
    @show = Show.new(show_params)
    if @show.save
      redirect_to @show
    else
      render 'new'
    end
  end

  def show
    @show = Show.find_by(id: params[:id])
  end

  def search
    if params[:search].blank?
    redirect_to('index', alert: "Empty field!") and return
    else
      @results = Show.getSearchedShows(params[:search].downcase)
    end
  end

  private

  def show_params
    params.require(:show).permit(:title, :favorite, :channel_id)
  end
end

show_reminder_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

show_reminder_app/app/helpers/application_helper.rb
module ApplicationHelper
end

show_reminder_app/app/helpers/channels_helper.rb
module ChannelsHelper
end

show_reminder_app/app/helpers/shows_helper.rb
module ShowsHelper
end

show_reminder_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

show_reminder_app/app/views/channels/index.html.erb
<h1>All Channels: </h1>

<% @channels.each do |channel| %>
  <div>
    <strong>Channel Name is: </strong>
    <%= channel.title %> <strong>Favorite:</strong> <%= channel.favorite %>
  </div>
<% end %>
<br/>
<br/>
<div>
  <%= link_to 'Add New Channel', new_channel_path %><br/>
  <%= link_to 'Back to home page', welcome_index_path %>
</div>

show_reminder_app/app/views/channels/new.html.erb
<h1>Add a New Channel</h1>

<div>
<%= form_for :channel, url: channels_path do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@channel.errors.count, "error") %> prohibited
        this channel from being saved:
      </h2>
      <ul>
        <% @channel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label "Enter Name:" %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "Favorite:" %><br>
    <%= f.check_box :favorite %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>
<div>
  <%= link_to 'Back to home page', welcome_index_path %>
</div>

show_reminder_app/app/views/channels/show.html.erb
<h1>Show Channel Details</h1>

<div>
  <strong>Channel Name is:</strong> <%= @channel.title %>
</div>

<div>
  <strong>Favorite:</strong> <%= @channel.favorite %>
</div>

<div>
  <%= link_to 'See All channel', channels_path %>
  <%= link_to 'Add New Channel', new_channel_path %>
  <%= link_to 'Back to home page', welcome_index_path %>
</div>

show_reminder_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShowReminderApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

show_reminder_app/app/views/shows/index.html.erb
<%= form_tag(search_path, :method => "get") do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search] %>
    <%= button_tag "Search",:name => nil%>
  </div>
<% end %>


<h1>All Shows: </h1>
<% @shows.each do |show| %>
  <div>
    <strong>Show Name is: </strong> <%= show.title %>
    <strong>Favorite: </strong> <%= show.favorite %>
    <strong>Associated With: </strong> <%= show.channel.title %>
  </div>
<% end %>
<br/>
<br/>
<div>
  <%= link_to 'Add New Show', new_show_path %><br/>
  <%= link_to 'Back to home page', welcome_index_path %>
</div>

show_reminder_app/app/views/shows/new.html.erb
<h1>Add a New Show</h1>

<div>
<%= form_for :show, url: shows_path do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@show.errors.count, "error") %> prohibited
        this channel from being saved:
      </h2>
      <ul>
        <% @show.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label "Enter Name:" %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "Favorite:" %><br>
    <%= f.check_box :favorite %>
  </p>

  <div>
    <%= f.label "Select Channel" %><br/>
    <%= f.select :channel_id, options_for_select( @channels.collect { |channel| [channel.title, channel.id] } ), {}, { class: 'form-control' } %>
  </div>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>
<div>
  <%= link_to 'Back to home page', welcome_index_path %>
</div>

show_reminder_app/app/views/shows/search.html.erb
<%= form_tag(search_path, :method => "get") do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search] %>
    <%= button_tag "Search",:name => nil%>
  </div>
<% end %>

<h3>Search Result:</h3>
<br/>

<% @results.each do |result| %>
  <div>
    <strong>Show Name is: </strong> <%= result.title %>
    <strong>Favorite: </strong> <%= result.favorite %>
    <strong>Associated With: </strong> <%= result.channel.title %>
  </div>
<% end %>

<br/>
<br/>

<%= link_to 'See All shows', shows_path %><br/>

show_reminder_app/app/views/shows/show.html.erb
<h1>Show Details</h1>

<div>
  <strong>Show Name is:</strong> <%= @show.title %>
</div>

<div>
  <strong>Favorite:</strong> <%= @show.favorite %>
</div>

<div>
  <strong>Show Associated With:</strong> <%= @show.channel.title %>
</div>
<br/>
<br/>

<div>
  <%= link_to 'See All shows', shows_path %><br/>
  <%= link_to 'Add New Show', new_show_path %><br/>
  <%= link_to 'Back to home page', welcome_index_path %>
</div>

show_reminder_app/app/views/welcome/index.html.erb
<h1>Welcome to the app</h1>
<br/>
<div><%= link_to 'See All channel', channels_path %></div>
<div><%= link_to 'Add New Channel', new_channel_path %></div>
<div><%= link_to 'See All shows', shows_path %></div>